version: '3'
services:
  light-control:
    image: rpi-light-control
    container_name: light-control
    restart: unless-stopped
    devices:
     - "/dev/lirc0:/dev/lirc0"
     - "/dev/video0:/dev/video0"
    privileged: true
    volumes:
      - /opt/light-training/photos:/photos
      - /var/run/dbus/:/var/run/dbus/:z
