version: '3'

services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    ports:
    - "8428:8428"
    - "4242:4242"
    - "8089:8089"
    volumes:
      - /data/victoriametrics:/storage
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    command:
      - "--storageDataPath=/storage"
#      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
      - "--retentionPeriod=99y"
      - "--selfScrapeInterval=20s"

