
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 
   - 0.0.0.0/1
   - 1.0.0.0/1

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
 - platform: mqtt
   unique_id: living_room_light
   name: "Living Room Light"
   command_topic: "home/living/light/toggle"
   state_topic: "home/living/light/status"
 - platform: mqtt
   unique_id: living_room_nightlight
   name: "Living Room Nightlight"
   command_topic: "home/living/light/toggle-night"
 - platform: mqtt
   unique_id: living_room_tv
   name: "Living Room TV"
   command_topic: "home/living/tv/toggle"
   state_topic: "home/living/tv/status"

mqtt:
  discovery: true
  broker: raspberrypi

alexa:
  smart_home:

# Shove history into ram
recorder:
  purge_keep_days: 2
  db_url: 'sqlite:///:memory:'

sensor:
  - platform: mqtt
    name: "AirQuality PM2.5 Bedroom"
    state_topic: "home/bedroom/air_quality"
    unit_of_measurement: "µg/m³"
    value_template: "{{ value_json.pm25 }}"
  - platform: mqtt
    name: "AirQuality PM10 Bedroom"
    state_topic: "home/bedroom/air_quality"
    unit_of_measurement: "µg/m³"
    value_template: "{{ value_json.pm10 }}"
  - platform: mqtt
    name: "AirQuality AQI Bedroom"
    state_topic: "home/bedroom/air_quality"
    unit_of_measurement: "AQI"
    value_template: "{{ value_json.aqi }}"

notify:
  - name: "Gmail"
    platform: smtp
    server: "smtp.gmail.com"
    port: 587
    timeout: 15
    sender: "mike.kaplinskiy+raspberrypi@gmail.com"
    encryption: starttls
    username: "mike.kaplinskiy@gmail.com"
    password: !secret gmail_password
    recipient:
      - "mike.kaplinskiy@gmail.com"
      - "veronica.kaplinskiy@gmail.com"
    sender_name: "Home Assistant"

  - name: "SMS"
    platform: smtp
    server: "smtp.gmail.com"
    port: 587
    timeout: 15
    sender: "mike.kaplinskiy+raspberrypi@gmail.com"
    encryption: starttls
    username: "mike.kaplinskiy@gmail.com"
    password: !secret gmail_password
    recipient:
      - !secret mike_phone_email
      - !secret v_phone_email
    sender_name: "Home Assistant"

