
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
   - 127.0.0.1

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  switch:
   - unique_id: living_room_tv
     name: "Living Room TV"
     command_topic: "home/living/tv/toggle"
     state_topic: "home/living/tv/status"

  sensor:
    - name: "AirQuality PM2.5 Bedroom"
      state_topic: "home/bedroom/air_quality"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm25 }}"
    - name: "AirQuality PM10 Bedroom"
      state_topic: "home/bedroom/air_quality"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm10 }}"
    - name: "AirQuality AQI Bedroom"
      state_topic: "home/bedroom/air_quality"
      unit_of_measurement: "AQI"
      value_template: "{{ value_json.aqi }}"

alexa:
  smart_home:

# Shove history into ram
recorder:
  purge_keep_days: 2
  commit_interval: 86400

notify:
  - name: "Gmail"
    platform: smtp
    server: "smtp.gmail.com"
    port: 587
    timeout: 15
    sender: "mike.kaplinskiy+raspberrypi@gmail.com"
    encryption: starttls
    username: "mike.kaplinskiy@gmail.com"
    password: !secret gmail_password
    recipient:
      - "mike.kaplinskiy@gmail.com"
      - "veronica.kaplinskiy@gmail.com"
    sender_name: "Home Assistant"

  - name: "SMS"
    platform: smtp
    server: "smtp.gmail.com"
    port: 587
    timeout: 15
    sender: "mike.kaplinskiy+raspberrypi@gmail.com"
    encryption: starttls
    username: "mike.kaplinskiy@gmail.com"
    password: !secret gmail_password
    recipient:
      - !secret mike_phone_email
      - !secret v_phone_email
    sender_name: "Home Assistant"


influxdb:
  api_version: 1
  host: raspberrypi
  port: 8428
  max_retries: 3
  measurement_attr: entity_id
  tags_attributes:
    - friendly_name
    - unit_of_measurement
  ignore_attributes:
    - icon
    - source
    - options
    - editable
    - min
    - max
    - step
    - mode
    - marker_type
    - preset_modes
    - supported_features
    - supported_color_modes
    - effect_list
    - attribution
    - assumed_state
    - state_open
    - state_closed
    - writable
    - stateExtra
    - event
    - friendly_name
    - device_class
    - state_class
    - ip_address
    - device_file
    - unit_of_measurement
    - unitOfMeasure
  include:
    domains:
      - sensor
      - binary_sensor
      - light
      - switch
      - cover
      - climate
      - input_boolean
      - input_select
      - number
      - lock
      - weather
  exclude:
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.glances*
      - sensor.time*
      - sensor.uptime*
      - sensor.dwd_weather_warnings_*
      - weather.weatherstation
      - binary_sensor.*_smartphone_*
      - sensor.*_smartphone_*
      - sensor.adguard_home_*
      - binary_sensor.*_internet_access

