version: '3'

services:
  nginx:
    image: rpi-nginx
    restart: unless-stopped
    volumes:
      - /opt/nginx/conf.d:/etc/nginx/conf.d:ro
      - /opt/nginx/certbot:/etc/letsencrypt
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
