version: '2.4'
services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    network_mode: host
    restart: always
    platform: linux/arm64/v8
    volumes:
      - /opt/mongodb:/data/db
  controller:
    image: rpi-unifi
    container_name: unifi_controller
    depends_on:
      - mongo
    init: true
    network_mode: host
    restart: always
    volumes:
      - /opt/unifi:/unifi/
    environment:
      DB_URI: mongodb://localhost/unifi
      STATDB_URI: mongodb://localhost/unifi_stat
      DB_NAME: unifi