version: '3'

services:
  nginx:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /opt/zigbee2mqtt/store/:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=America/Los_Angeles
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
